### ISSUE TITLE
minimum size for window

### ISSUE THREAD

**Issue by netfun81** [sinapinto/tfwm#1]
Nice wm so far.  I know you are in early development, so I thought you might look into this issue.   

If I open Firefox it appears as a tiny window in the center of the screen.   Resizing the window using the HLJK keys or maximize function works, but after closing and reopening it is back to a tiny size.   When i open Firefox under other stacking (floating) window managers it is nearly full screen (1440x900).  I have tried resizing under openbox and then going back into bwm with the same results.   Other programs such as thunar, geany, etc seem to work properly so it may be the problem is with firefox, however other  window managers have somehow avoided this maybe by setting a minimum window size?

**Comment by sinapinto** [comment]
Hi,
This happens because bwm currently does not respect the size hints set by windows.  (for the meantime, you can manually fullscreen it with `Mod+a`).

I will work on fixing this next.  Thanks for opening an issue.

**Comment by sinapinto** [comment]
Ok, so it looks like firefox initially sends a configure request to be resized to 300 x 200.   However, if you have the setting `"When firefox starts: Show my windows and tabs from last time"` enabled in firefox, firefox will remember the dimensions it was from the previous session, and open at that size.  Otherwise, it will always open at 300 x 200.

With this last commit, bwm should now resize firefox as it should.
